### ISSUE TITLE
Hosts are automatically added to "hcloud" group in dynamic inventory

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible-collections/hetzner.hcloud#114]
##### SUMMARY

https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_inventory.html does not mention anywhere that hosts will get added to a group by default. This is also not configurable.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hetzner.hcloud.hcloud inventory plugin

##### COLLECTION VERSION

```paste below
1.6.0
```

##### STEPS TO REPRODUCE

configure inventory plugin for access to any project, e.g. like this:

```yaml
---
# foo.hcloud.yaml
plugin: hetzner.hcloud.hcloud
token: "supersecret readonly token"
```

check this inventory using `ansible-inventory -i ./foo.hcloud.yaml --graph`

##### EXPECTED RESULTS

```
@all:
  |--foo
  |--bar
  |--@ungrouped:

```

If this is just deemed a documentation error and intended to work this way, please also allow me to turn this off. I'd much rather have a group hierarchy in my inventory (the group `hcloud` contains only other groups - one per project - not hosts) and this plugin keeps messing with this by adding all hosts. If I really want/need the current behavior, I can easily already do this via:

```yaml
---
# foo.hcloud.yaml
plugin: hetzner.hcloud.hcloud
token: "supersecret readonly token"
groups:
  hcloud: name != ''
```

The offending line is this one: by the way https://github.com/ansible-collections/hetzner.hcloud/blob/51865c29ab306b60be88963e81687761260eae4b/plugins/inventory/hcloud.py#L258-L262

##### ACTUAL RESULTS

```
@all:
  |--@hcloud:
  |  |--foo
  |  |--bar
  |--@ungrouped:

```
