### ISSUE TITLE
Inventory: allow custom hostname using templates

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible-collections/hetzner.hcloud#115]
##### SUMMARY

Currently the server's name as defined in the hetzner cloud console is used as `ansible_hostname` (see https://github.com/ansible-collections/hetzner.hcloud/blob/51865c29ab306b60be88963e81687761260eae4b/plugins/inventory/hcloud.py#L262) --> `server.name`

This means if in a single play several projects are used (and each contains e.g. a server named `web`) there will be issues. Especially if not all projects are managed by the same people, so it can be hard to enforce a globally unique naming scheme.

There are some fancy things possible with this idea I assume, but a simple one would be to first modify the discovered host's variables before adding it to the inventory.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hetzner.hcloud.hcloud inventory plugin

##### ADDITIONAL INFORMATION

```yaml
---
plugin: hetzner.hcloud.hcloud
token: "supersecret readonly token"
hosts:
  # Set these host variables to these values before adding them to the inventory.
  ansible_hostname: "customer01_{{ name }}"
```
