### ISSUE TITLE
Storagebox ssh key management

### ISSUE THREAD

**Issue by EHEX-schildt** [ansible-collections/hetzner.hcloud#119]
##### SUMMARY
It would be a grat Help if we could manage storagebox ssh key's like hetzner.hcloud.hcloud_ssh_key
Maybe with sub-account support.
https://docs.hetzner.com/de/robot/storage-box/backup-space-ssh-keys/
https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_ssh_key_module.html#ansible-collections-hetzner-hcloud-hcloud-ssh-key-module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hetzner.hcloud.hcloud_storagebox_ssh_key ?

##### ADDITIONAL INFORMATION

```yaml
- name: Create a basic ssh_key
  hcloud_storagebox_ssh_key:
    user: u123456
    server: u123456.your-storagebox.de
    public_key: "ssh-rsa AAAjjk76kgf...Xt"
    state: present
- name: remove old ssh_key
  hcloud_storagebox_ssh_key:
    user: u123456-sub1
    server: u123456.your-storagebox.de
    public_key: "ssh-rsa AAAjjk76kgf...Xt"
    state: absent
```
