### ISSUE TITLE
couldn't resolve module/action 'hcloud_load_balancer'

### ISSUE THREAD

**Issue by JannikZed** [ansible-collections/hetzner.hcloud#123]
##### SUMMARY
I'm using this amazing playbook since some time without any issues - but strangely, I can't use anything related to load_balancers.

Here the code: 
```
- name: Add all servers to network
  hcloud_server_network:
    server: "{{ item }}" 
    network: internal
  with_inventory_hostnames:
    - worker-*
    - control-*
    - etcd-*
  register: internal_network

- name: Add the incoming master loadbalancer
  hcloud_load_balancer:
    name: ingress-lb
    load_balancer_type: lb11
    location: nbg1
    state: present
```

the `hcloud_server_network` works great - but the loadbalancer fails: 

```
TASK [Create kube control node NBG1] ************************************************************************************************
ok: [localhost]

TASK [Create kube etcd node] ********************************************************************************************************
ok: [localhost]

TASK [Refresh inventory] ************************************************************************************************************

PLAY [localhost] ********************************************************************************************************************

TASK [include_tasks] ****************************************************************************************************************
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'hcloud_load_balancer'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/Users/jannik/Documents/git/infrastructure-common/ansible/roles/hetzner-network-lb.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add the incoming master loadbalancer\n  ^ here\n"}

PLAY RECAP **************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hcloud_load_balancer,  hcloud_load_balancer_target

##### ANSIBLE VERSION

```paste below
  config file = /Users/jannikzinkl/Documents/git/infrastructure-common/ansible/ansible.cfg
  configured module search path = ['/Users/jannik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jannik/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:48:04) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below

# /Users/jannik/.ansible/collections/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 1.6.0  

# /usr/local/lib/python3.9/site-packages/ansible_collections
Collection     Version
-------------- -------
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
