### ISSUE TITLE
add support of inventory caching to the `hcloud` inventory plugin

### ISSUE THREAD

**Issue by tagirb** [ansible-collections/hetzner.hcloud#124]
##### SUMMARY
Currently the `hcloud` inventory plugin does not support Ansible caching plugins, which means that dynamic inventory needs to be re-created using Hetzner Cloud API every time it is used, which may take time for large environments and also increases the load of the Hetzner Cloud API.

##### ISSUE TYPE
- add support of caching plugins to the `hcloud` inventory plugin

##### COMPONENT NAME
`hetzner.hcloud` inventory plugin

##### ADDITIONAL INFORMATION
Here's an inventory file example derived from the `aws_ec2` inventory plugin:

```yaml
---
plugin: hcloud
token: <token>
locations: ['nbg1']

cache: yes
cache_plugin: ansible.builtin.jsonfile
cache_timeout: 7200
cache_connection: ./
cache_prefix: myproject
```

The `aws_ec2` inventory plugin does already support this feature and can be used as an implementation example, looks quite simple:
https://github.com/ansible-collections/amazon.aws/blob/main/plugins/inventory/aws_ec2.py
