### ISSUE TITLE
hcloud_server_info return error if server have not IPV6 address

### ISSUE THREAD

**Issue by fdaforno** [ansible-collections/hetzner.hcloud#148]
##### SUMMARY

Dear all,
i get error if i create a server WITHOUT IPV6 address . 
temporary workaround to skip this issue is to enable ipv6  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hcloud_server_info

##### ANSIBLE VERSION
```
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.5 (main, Jul 25 2022, 15:52:08) [GCC 11.2.1 20220219]
  jinja version = 3.1.2
  libyaml = False

```

##### COLLECTION VERSION

```
Collection        Version
----------------- -------
community.general 5.3.0 
```

##### OS / ENVIRONMENT
alpine

##### STEPS TO REPRODUCE

```yaml
- name: Create server WHITOUT IPV6
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ item.server_name }}"
    # networks: dc-network
    server_type: "{{ item.server_type }}"
    image: "{{ os_version }}"
    location: "{{ datacenter_location }}"
    backups: false
    enable_ipv6: false
    enable_ipv4: true
    upgrade_disk: false
    ssh_keys: "{{ ssh_public_keys | map(attribute='key_name') | list }}"
    state: started
  register: servercreated
  loop: "{{ servers }}"


- hosts: localhost
  gather_facts: no
  become: false
  tasks:
    - local_action:
       module: hcloud_server_info
       api_token: "{{ hcloud_token }}"
      register: info_vm
    - debug: var=info_vm

```

##### EXPECTED RESULTS

`TASK [hcloud_server_info] ****************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'ip'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1660594749.4064791-4182-49610997880726/AnsiballZ_hcloud_server_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1660594749.4064791-4182-49610997880726/AnsiballZ_hcloud_server_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1660594749.4064791-4182-49610997880726/AnsiballZ_hcloud_server_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server_info', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server_info', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_info_payload_vyy5y97n/ansible_hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_info.py\", line 232, in <module>\n  File \"/tmp/ansible_hcloud_server_info_payload_vyy5y97n/ansible_hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_info.py\", line 217, in main\n  File \"/tmp/ansible_hcloud_server_info_payload_vyy5y97n/ansible_hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/module_utils/hcloud.py\", line 63, in get_result\n  File \"/tmp/ansible_hcloud_server_info_payload_vyy5y97n/ansible_hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_info.py\", line 160, in _prepare_result\nAttributeError: 'NoneType' object has no attribute 'ip'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

##### ACTUAL RESULTS

```paste below

```
