### ISSUE TITLE
Feature: Ability to set private static IP for private networks

### ISSUE THREAD

**Issue by varuzam** [ansible-collections/hetzner.hcloud#172]
##### SUMMARY
A while ago support for private network was added https://github.com/ansible-collections/hetzner.hcloud/commit/ad8958a2ad3ff060df01a275a594419ed100c27e
But there is no way to set static private ip. It would be nice to have this ability.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hetzner.hcloud.server module

##### ADDITIONAL INFORMATION
```yaml
- name: Create server
    hetzner.hcloud.hcloud_server:
      name: serv1
      private_networks::
        - name: net1
          ipv4_address: 10.1.0.1
        - name: net2
          ipv4_address: 10.2.0.1
      ...

```

**Comment by NavidSassan** [comment]
Hi, we have a similar problem. Our goal is to create a VM that only has a static IP in a private network and no public IP.

* we managed to assign a static IP to a server using the `hcloud_server_network` module after creating a server *with* a public IP
* what also works is to create a server without a public IP and with a private network, but not with a static IP
* creating a server with only a private network and a static IP fails:
    * since the `private_networks` key in `hcloud_server` does not support a static IP, we tried not using it. This leads to `invalid input: server must be attached to at least one of: primary_ipv4, primary_ipv6, private_network`
    * already attaching the server to the network using `private_networks` and then trying to change the IP to static using `hcloud_server_network` afterwards does not do anything (unchanged / OK in ansible)

You can find the detailed tasks in our role [here](https://github.com/Linuxfabrik/lfops/tree/main/roles/hetzner_vm).

Possible solutions:
* remove the restriction that a server needs to have either a public or a private IP. Then one can just use the `hcloud_server_network` module.
* implement setting the IP via `private_network` as mentioned above in the original post
* do something like openstack, and allow creating a "port" with a network / static IP, which then is attached to the server. However, this is a little more complicated to use (you can see the handling of that in our [infomaniak_vm role](https://github.com/Linuxfabrik/lfops/tree/main/roles/infomaniak_vm))

**Comment by github-isomorph** [comment]
Hi, I also have a similar problem.  I am using Ansible to create a server in the Hetzner cloud. My aim is to integrate the new
server into a private network that I have previously created. The server should not be accessible via the internet, so I have disabled ipv4 and ipv6. Rather, I'd like to access the server by connecting via OpenVPN to the private network 'ipfire' and connect by use of ssh from there.

**Comment by janre** [comment]
Same for me. The only workaround for us currently is to create a server with public ip and manually add it to a network with a static IP, then disable the public ip again.

**Comment by jooola** [comment]
While I understand implementing this in the server module might make your lives easier, what do you folks think about this:

https://github.com/ansible-collections/hetzner.hcloud/blob/c8e6a84b0bcd96d7e5eb1a76ce532ed3adde68ad/examples/server-with-private-ip-only.yml#L28-L50

**Comment by laurikari** [comment]
Creating the server in stopped state works for my use case, thanks for the tip!

**Comment by apricote** [comment]
@jooola is on vacation this week, but will be back on Monday.

@varuzam maybe the [`check_mode` can help you there. You can run the `hetzner.hcloud.server_network` in check mode first, to see if any changes would be made and only shutdown the server if needed. Some pseudo code:

```yaml
tasks:
- name: Check if private IP needs to be changed
  hetzner.hcloud.server_network: 
    network: my-network
    server: "{{ name }}"
    ip: "{{ private_ip }}"
    state: present
    check_mode: true
  register: ip_changes

- name: Update private IP
  if: ip_changes is changed # Or `ip_changes.changed == true`
  block:
    - name: Shutdown Server
      # ...
    - name: Update IP
      # ...
    - name: Start Server
      # ...
```

- https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html#using-check-mode
- https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#changed
- https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#conditions-based-on-registered-variables
- https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html
