### ISSUE TITLE
Regression: Release 1.9.0 now requires explicit mentions of private networks

### ISSUE THREAD

**Issue by asciiprod** [ansible-collections/hetzner.hcloud#174]
##### SUMMARY
Restarting an instance will detach any private networks unless they are explicitly mentioned.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
* `hcloud_server`

##### STEPS TO REPRODUCE
* Create private network and subnet
* Attach server to network
* Restart server (network gets detached)

```yaml
- name: Attach server to network
  hetzner.hcloud.hcloud_server_network:
    api_token: "{{ hcloud_api_token }}"
    network: "{{ private_network_name }}"
    server: "{{ hc_hostname }}"
    state: present
  delegate_to: localhost

- name: Wait a few seconds
  ansible.builtin.pause:
    seconds: 10

- name: Reset server via API
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_api_token }}"
    name: "{{ hc_hostname }}"
    state: restarted
  delegate_to: localhost
```

Workaround is to include the private network in the restart:

```yaml
 hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_api_token }}"
    name: "{{ hc_hostname }}"
    private_networks:
      - "{{ private_network_name }}"
    state: restarted
```

##### EXPECTED RESULTS
* private network remains attached

##### ACTUAL RESULTS
* private network gets detached

**Comment by EHEX-schildt** [comment]
We got a similar Problem: if we update a server label with:
```
hcloud_label_add:
  test: abc
```
```
- name: Get hcloud_server_info
  hetzner.hcloud.hcloud_server_info:
    name: "{{ hcloud_label_server }}"
    api_token: "{{ hcloud_label_api_token }}"
  register: hcloud_server_info
- name: Add server labels
  hetzner.hcloud.hcloud_server:
    name: "{{ hcloud_server }}"
    labels: "{{ hcloud_server_info.hcloud_server_info[0].labels | combine(hcloud_label_add) }}"
    api_token: "{{ hcloud_label_api_token }}"
```

**EXPECTED RESULTS**
  private network remains attached
**ACTUAL RESULTS**
  private network gets detached
