### ISSUE TITLE
hcloud_server - Create a storage box

### ISSUE THREAD

**Issue by doczkal** [ansible-collections/hetzner.hcloud#197]
##### SUMMARY
As a user I would expect to be able to manage storage boxes https://www.hetzner.com/de/storage/storage-box just like servers. With create, remove, resize options

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hetzner.hcloud.hcloud_server or (new module) hetzner.hcloud.hcloud_storage_box ?

##### ADDITIONAL INFORMATION
Automate create, remove, resize of storage boxes

```yaml
- name: Create a storage box
  hcloud_server:
    name: my-server
    server_type: bx11
    state: present

- name: Create a storage box server with ssh key
  hcloud_server:
    name: my-server
    server_type: bx11
    location: fsn1
    ssh_keys:
      - me@myorganisation
    state: present

- name: Resize an existing server
  hcloud_server:
    name: my-server
    server_type: bx21
    upgrade_disk: yes
    state: present

```
