### ISSUE TITLE
hcloud_firewall multiple ports?

### ISSUE THREAD

**Issue by ghost** [ansible-collections/hetzner.hcloud#202]
Hi,

is it possible to add multiple Ports to the ports option in the hcloud_firwall module?

Right now it does not work and i'm getting an error (maybe I'm doing something wrong).

Here i want to create a Firewall Rule for Port 80 and 443 and i'm getting an error.

Example:
```
 - name: Firewall-Testrule
      hetzner.hcloud.hcloud_firewall:
        api_token: "{{ hcloud_token }}"
        name: firewall-www
        rules:
          - direction: in
            protocol: tcp
            port: 80, 443
            source_ips:
              - 0.0.0.0/0
              - ::/0
            description: www
        state: present
```

I also tried this.
Doing it separetly it overrides the old Rule so only the Rule with Port 443 will be applied.

Example:
```
    - name: Firewall-Testrule
      hetzner.hcloud.hcloud_firewall:
        api_token: "{{ hcloud_token }}"
        name: firewall-www
        rules:
          - direction: in
            protocol: tcp
            port: 80
            source_ips:
              - 0.0.0.0/0
              - ::/0
            description: www
        state: present
     
    - name: Firewall-Testrule
      hetzner.hcloud.hcloud_firewall:
        api_token: "{{ hcloud_token }}"
        name: firewall-www
        rules:
          - direction: in
            protocol: tcp
            port: 443
            source_ips:
              - 0.0.0.0/0
              - ::/0
            description: www
        state: present
```
Does someone have a soultion?

Thanks in advance!
