### ISSUE TITLE
hcloud_server_network doesnt attach requested IP

### ISSUE THREAD

**Issue by liKe2k1** [ansible-collections/hetzner.hcloud#255]
##### SUMMARY

If I create a server and attach it to a private network and then assign the IP from a subnet, nothing happens.

For example:

Data

```
network_name: net-region
network_region: 10.145.0.0/16
default_os: rocky-9
region: fsn1

subnets:
 - name: management
   ip_range: 10.145.1.0/24
 - name: kubernetes
   ip_range: 10.145.5.0/24
 - name: client
   ip_range: 10.145.10.0/24

servers:
   - name: lvjump01
      ip: 10.145.1.11
      network: management
      type: cpx11
      domain: "{{ stage }}"
      public: false
```

Will execute in a the network creation

```
- name: create a the internal network
  hcloud_network:
    api_token: "{{ hcloud_token }}"
    name: "{{ network_name }}"
    ip_range: "{{ network_region }}"
    state: present
  run_once: true
  delegate_to: localhost

- name: create subnets
  hcloud_subnetwork:
    api_token: "{{ hcloud_token }}"
    network: "{{ network_name }}"
    ip_range: "{{ item.ip_range }}"
    network_zone: eu-central
    type: cloud
    state: present
  with_items: "{{ subnets }}"
  run_once: true
  delegate_to: localhost
```

Then, the server will be created in a loop:

```
- name: Create server
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ item.name }}"
    server_type: "{{ item.type }}"
    image: "{{ default_os }}"
    location:  "{{ region }}"
    state: started
    ssh_keys: "{{ ssh_keys }}"
    private_networks:
      - "{{ network_name }}"
  register: create_vm
  delegate_to: localhost
  run_once: true
```

This part always state CHANGED

```
- name: Attach private ip
  hcloud_server_network:
    network: "{{ network_name }}"
    server: "{{ item.name }}"
    ip: "{{ item.ip }}"
    state: present
  delegate_to: localhost
  run_once: true`
```

But the VM has a default IP in a random subnet.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Maybe hcloud_server_network

##### ANSIBLE VERSION
```
ansible [core 2.14.2]
  config file = /home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg
  configured module search path = ['/home/toby/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/toby/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, May 24 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection     Version
-------------- -------
hetzner.hcloud 1.15.0
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg) = True
CONFIG_FILE() = /home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg
DEFAULT_HOST_LIST(/home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg) = ['/home/toby/git/private/XXX/infrastructure/iaac-cluster/inventory.ini']
DEFAULT_LOCAL_TMP(/home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg) = /home/toby/.ansible/tmp/ansible-local-63827brkq7kgb
DEFAULT_ROLES_PATH(/home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg) = ['/home/toby/git/private/XXX/infrastructure/iaac-cluster/roles']
DEPRECATION_WARNINGS(/home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg) = False
HOST_KEY_CHECKING(/home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg) = False
INJECT_FACTS_AS_VARS(/home/toby/git/private/XXX/infrastructure/iaac-cluster/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Rocky Linux release 9.2 (Blue Onyx)

##### STEPS TO REPRODUCE
see description

##### EXPECTED RESULTS

Server should assigned to defined private ip in the target subnet

##### ACTUAL RESULTS

Server get a random ip from a random subnet

**Comment by jooola** [comment]
Hi @liKe2k1,

I was able to reproduce your problem, and the server gets a random/first IP from the "net-region" network IP range (10.145.0.0/16).

To attach the desired IP (10.145.1.11), you can try removing the `private_networks` entry when creating the server. When using this field, you will ask to attach an IP within the IP range of that network (10.145.0.0/16). And let the `hetzner.hcloud.hcloud_server_network` module attach the correct IP.

Here is my reproduction playbook:
```yml
- hosts: all
  vars:
    hcloud_token: some_token

    network_name: net-region
    network_region: 10.145.0.0/16
    default_os: rocky-9
    region: fsn1

    subnets:
      - name: management
        ip_range: 10.145.1.0/24
      - name: kubernetes
        ip_range: 10.145.5.0/24
      - name: client
        ip_range: 10.145.10.0/24

    servers:
      - name: lvjump01
        ip: 10.145.1.11
        network: management
        type: cpx11
  tasks:
    - name: Create the internal network
      hetzner.hcloud.hcloud_network:
        api_token: "{{ hcloud_token }}"
        name: "{{ network_name }}"
        ip_range: "{{ network_region }}"
        state: present
      run_once: true
      delegate_to: localhost

    - name: Create subnets
      hetzner.hcloud.hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: "{{ network_name }}"
        ip_range: "{{ item.ip_range }}"
        network_zone: eu-central
        type: cloud
        state: present
      with_items: "{{ subnets }}"
      run_once: true
      delegate_to: localhost

    - name: Create a server
      hetzner.hcloud.hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ servers[0].name }}"
        server_type: "{{ servers[0].type }}"
        image: "{{ default_os }}"
        location: "{{ region }}"
        ## Comment this out to prevent attaching a random IP from the "{{ network_name }}" ip range.
        #private_networks:
        #  - "{{ network_name }}"
        state: started
      delegate_to: localhost
      run_once: true

    - name: Attach a private ip
      hetzner.hcloud.hcloud_server_network:
        api_token: "{{ hcloud_token }}"
        network: "{{ network_name }}"
        server: "{{ servers[0].name }}"
        ip: "{{ servers[0].ip }}"
        state: present
      delegate_to: localhost
      run_once: true
```

 I hope this helps ?
