### ISSUE TITLE
Cannot create floating ip

### ISSUE THREAD

**Issue by ddozza** [ansible-collections/hetzner.hcloud#29]
This is the error I receive when I try to create a floating IP.
```ERROR! couldn't resolve module/action 'hcloud_floating_ip'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/davide/Projects/K8s/ansible/floating_ip.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Create a basic IPv4 Floating IP
      ^ here
```

The playbook looks like:

```
- name: Create Basic Server
  hosts: localhost
  connection: local
  gather_facts: False
  user: root
  vars:
    hcloud_token: xxxxxxxxxxxxxxxxx
  tasks:
    - name: Create a basic IPv4 Floating IP
      hcloud_floating_ip:
        api_token: "{{ hcloud_token }}"
        name: "my-floating-ip"
        home_location: "fsn1"
        type: ipv4
        state: present
      register: floatingIP 
```
Any suggestion?
