### ISSUE TITLE
Floating IP Idempotency

### ISSUE THREAD

**Issue by ohdearaugustin** [ansible-collections/hetzner.hcloud#31]
# Floating IP Idempotency

The floating ip module is not idempotent, when you rerun the task on the same server it will show up as changed.

Example:
```
- name: Create floating ip
  hetzner.hcloud.hcloud_floating_ip:
      api_token: "{{ hcloud_token }}"
      name: test-ip
      server: test-server
      force: true
      type: ipv4
      state: present
```

PR otw
