### ISSUE TITLE
I am unable to create a server with a given static private ip in a private subnet through Ansible

### ISSUE THREAD

**Issue by samiksha1191** [ansible-collections/hetzner.hcloud#356]
Hello Hetzner team,

I am trying to create servers with static ip in the hetzner private subnet using this collection **hetzner.hcloud.hcloud_server_network** module

But I am getting error.

can you please help to understand the requirement for parameters for this module as I have checked already, the **ansible version** and the **[hetzner.hcloud collection](https://galaxy.ansible.com/ui/repo/published/hetzner/hcloud/)** version is already as per the requirement.

Below is snippet of my code.

```yml
- name: Create a basic network
  hetzner.hcloud.hcloud_network:
    name: "{{ item.name }}"
    ip_range: "{{ item.ip_range }}"
    state: "{{ infrastructure_state }}"
    api_token: "{{ hcloud_token }}"
  with_items: "{{ networks }}"

- name: Create a basic subnetwork
  hcloud_subnetwork:
    network: network1
    ip_range:  "{{ item.ip_range }}"
    network_zone: eu-central
    type: cloud
    state: present
    api_token: "{{ hcloud_token }}"

- name: Create a basic server
  hcloud_server:
    name: my-server
    server_type: cx11
    image: ubuntu-22.04
    state: present                                            
    enable_ipv4: false
    enable_ipv6: false
    datacenter: nbg1-dc3
    private_networks:
       - network1
    api_token: "{{ hcloud_token }}"

- name: Create a server network and specify the ip address
  hcloud_server_network:
    network: network1
    server: my-server 
    ip: 10.0.1.10
    state: present
    api_token: "{{ hcloud_token }}"_**
    

```

here is my var file details
```yml
hcloud_token: 'mytoken'
h_server_type: 'cx11'
h_server_location: 'nbg1-dc3'
infrastructure_state: 'present'
h_server_image: 'ubuntu-22.04'
h_server_ipv4: 'false'
h_server_ip6: 'false'
server_names: 
  - name: controlplane1
  - ip: 10.0.1.10
  - name: controlplane2
  - ip: 10.0.1.11
  - name: controlplane3
  - ip: 10.0.1.12
ssh_keys_to_create:
  - name: key1
    public_key: "key1"
  - name: key2
    public_key: "key2"


firewalls:
    - name: firewall-1
      rules:
        - direction: in
          protocol: tcp
          port: "22"
          source_ips:
            - "0.0.0.0/0"  # Replace with your desired source IP range
        - direction: in
          protocol: tcp
          port: "80"
          source_ips:
              - "0.0.0.0/0" 

    - name: firewall-2
      rules:
        - direction: in
          protocol: tcp
          port: "443"
          source_ips:
              - "0.0.0.0/0"  # Replace with your desired source IP range
        - direction: in
          protocol: udp
          port: "53"
          source_ips:
              - "0.0.0.0/0" 

networks:
    - name: network1
      ip_range: 10.0.1.0/24

```

and below is the error I am getting
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'id'
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/skumari@HW.local/.ansible/tmp/ansible-tmp-1697126149.5867987-348936-35988868528118/AnsiballZ_hcloud_server_network.py", line 107, in <module>
        _ansiballz_main()
      File "/home/skumari@HW.local/.ansible/tmp/ansible-tmp-1697126149.5867987-348936-35988868528118/AnsiballZ_hcloud_server_network.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/skumari@HW.local/.ansible/tmp/ansible-tmp-1697126149.5867987-348936-35988868528118/AnsiballZ_hcloud_server_network.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server_network', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server_network', _modlib_path=modlib_path),
      File "/usr/lib/python3.10/runpy.py", line 224, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_hcloud_server_network_payload_uice73nc/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py", line 240, in <module>
      File "/tmp/ansible_hcloud_server_network_payload_uice73nc/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py", line 234, in main
      File "/tmp/ansible_hcloud_server_network_payload_uice73nc/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py", line 190, in present_server_network
      File "/tmp/ansible_hcloud_server_network_payload_uice73nc/ansible_hcloud_server_network_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_network.py", line 147, in _get_server_network
    AttributeError: 'NoneType' object has no attribute 'id'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1_

```

EDIT(jooola): format

**Comment by samiksha1191** [comment]
Hi @apricote can you please here as I am blocked for long time now on this issue. your help here is greatly appreciated.

**Comment by jooola** [comment]
Hello @samiksha1191 

I think the error you are facing is because one of the server or network does not exist (is not found). The error should be improved, I'll fix this.

But is unrelated to your questions: here are a few comments for the code you provided:

```yaml
- name: Create a basic network
  hetzner.hcloud.hcloud_network:
    name: "{{ item.name }}"
    ip_range: "{{ item.ip_range }}"
    state: "{{ infrastructure_state }}"
    api_token: "{{ hcloud_token }}"
  with_items: "{{ networks }}"

- name: Create a basic subnetwork
  # Make sure to use fqcn when calling the collection modules: hetzner.hcloud.hcloud_subnetwork
  hcloud_subnetwork:
    # I assume you are refering to {{ networks[0].name }}
    network: network1
    # You should use a different ip_range for your network and subnetwork, e.g.
    # 10.0.0.0/8 for the network and only a /16 or /24 for a subnetwork, say 10.0.1.0/24
    ip_range: "{{ item.ip_range }}"
    network_zone: eu-central
    type: cloud
    state: present
    api_token: "{{ hcloud_token }}"

- name: Create a basic server
  # Make sure to use fqcn when calling the collection modules: hetzner.hcloud.hcloud_server
  hcloud_server:
    name: my-server
    server_type: cx11
    image: ubuntu-22.04
    state: present
    enable_ipv4: false
    enable_ipv6: false
    datacenter: nbg1-dc3
    # This will automatically attach a random private ip from the subnet to your server, since you
    # want to specific the private IP yourself in the next task, you should not use this
    # argument.
    private_networks:
      - network1
    api_token: "{{ hcloud_token }}"

- name: Attach a server to a private network
  # Make sure to use fqcn when calling the collection modules: hetzner.hcloud.hcloud_server_network
  hcloud_server_network:
    # I assume you are refering to {{ networks[0].name }}
    network: network1
    server: my-server
    ip: 10.0.1.10
    state: present
    api_token: "{{ hcloud_token }}"
```

**Comment by jooola** [comment]
Related to https://github.com/ansible-collections/hetzner.hcloud/issues/255

**Comment by samiksha1191** [comment]
Hi @jooola Please don't mark the ticket as closed just yet as the problem is not solved until yet at my end. Allow me sometime until today EOD to confirm back.

**Comment by samiksha1191** [comment]
Hi @jooola If i am following the instruction you gave above then yes my server now has a private IP of my choice but it is still coming up with a public IP because I can not keep both as false.

   **enable_ipv4
   enable_ipv6**

so i commented them in the code but then now it is assuming that since i have declared any value for the above two parameters, so it is by default assigning one ipv4 address.

In my use case I d not want to have any public IP attached to the server at all. can you please tell me how do i achieve the same?

FYI, my current code looks like below.


    **_- name: Create a basic server
      hcloud_server:
        name: my-server
        server_type: cx11
        image: ubuntu-22.04
        state: present                                            
        # enable_ipv4: false
        # enable_ipv6: false
        datacenter: nbg1-dc3
        #private_networks:
           #- network1
        api_token: "{{ hcloud_token }}"

    - name: Create a server network and specify the ip address
      hcloud_server_network:
        network: network1
        server: my-server 
        ip: 10.0.1.10
        state: present
        api_token: "{{ hcloud_token }}"_**

**Comment by samiksha1191** [comment]
Hi @jooola and now I have tried your lines of code as well from the issue #255 but it is still giving me public IP.

Please help here as it is blocking to move further. PFB screenshot FYR.


![image](https://github.com/ansible-collections/hetzner.hcloud/assets/40717941/b2d503e4-db2e-416c-a0ee-6000050925bd)


The code written to spin up this server now is 


    **_- name: Create a server
      hetzner.hcloud.hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: my-server
        server_type: cx11
        image: ubuntu-22.04
        location: nbg1
        ## Comment this out to prevent attaching a random IP from the "{{ network_name }}" ip range.
        #private_networks:
        #  - "{{ network_name }}"
        state: started
      delegate_to: localhost
      run_once: true

    - name: Create a server network and specify the ip address
      hetzner.hcloud.hcloud_server_network:
        network: network1
        server: my-server 
        ip: 10.0.1.10
        state: present
        api_token: "{{ hcloud_token }}"
      delegate_to: localhost
      run_once: true_**

**Comment by samiksha1191** [comment]
Hi @apricote can you please here as well?

**Comment by jooola** [comment]
Hello @samiksha1191 

A server without any network cannot be started. So you can create a server that is `stopped`, attach your private ip, and start the server afterward. Here is an example:

```yaml
- name: Create server with a private ip and no public ip
  hosts: localhost
  connection: local
  tasks:
    - name: Create a server
      hetzner.hcloud.hcloud_server:
        name: my-server
        server_type: cx11
        image: ubuntu-22.04
        location: nbg1
        enable_ipv4: false
        enable_ipv6: false
        state: stopped

    - name: Attach private ip to server
      hetzner.hcloud.hcloud_server_network:
        network: network1
        server: my-server
        ip: 10.0.1.10
        state: present

    - name: Start the server
      hetzner.hcloud.hcloud_server:
        name: my-server
        state: started

```

Also, a few tips for any future bug report:
- You can wrap your code between triple backticks  \` to format it,  `**_   _**` is not a valid Markdown syntax, at least on Github.
- Make sure to give all information about your problem in the initial report.
