### ISSUE TITLE
dns module

### ISSUE THREAD

**Issue by markuman** [ansible-collections/hetzner.hcloud#36]
##### SUMMARY
Add a module to use hetzner dns robot to set dns records.

##### ISSUE TYPE
- Feature Idea

**Comment by markuman** [comment]
So the problem might be, that "hcloud" and "dns" are two different products in the point of view of hetzner.  
You need to create different api token to the dns service.

I made a collection for my own to cover this gap: https://galaxy.ansible.com/markuman/hetzner_dns  

```yml
---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create a basic server
      hcloud_server:
        api_token: "{{ HCLOUD_TOKEN }}"
        name: my-server
        server_type: cx11
        image: ubuntu-18.04
        state: present
      register: INSTANCE

    - name: add record for my-server
      markuman.hetzner_dns.record:
        api_token: "{{ DNS_TOKEN }}"
        zone_name: osuv.de
        name: my-server
        value: "{{ INSTANCE.hcloud_server.ipv4_address }}"
        type: A
        ttl: 300

```
