### ISSUE TITLE
hcloud_server delete_protection and rebuild_protection can't be applied

### ISSUE THREAD

**Issue by omerfsen** [ansible-collections/hetzner.hcloud#376]
##### SUMMARY
Even if we state  delete_protection and rebuild_protection  as true on hcloud_server it is not respected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hcloud_server

##### ANSIBLE VERSION

```
ansible [core 2.15.5]
  config file = /home/osen/projects/ansible-automation/ansible.cfg
  configured module search path = ['/home/osen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/osen/venvs/ansible_8.5.0/lib/python3.10/site-packages/ansible
  ansible collection location = /home/osen/.ansible/collections
  executable location = /home/osen/venvs/ansible_8.5.0/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/osen/venvs/ansible_8.5.0/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
[2.2.0](https://github.com/ansible-collections/hetzner.hcloud/releases/tag/2.2.0)
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/home/osen/projects/ansible-automation/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/osen/projects/ansible-automation/ansible.cfg) = /tmp/facts_cache
COLLECTIONS_PATHS(/home/osen/projects/ansible-automation/ansible.cfg) = ['/home/osen/.ansible/collections']
CONFIG_FILE() = /home/osen/projects/ansible-automation/ansible.cfg
DEFAULT_GATHERING(/home/osen/projects/ansible-automation/ansible.cfg) = smart
DEFAULT_LOCAL_TMP(/home/osen/projects/ansible-automation/ansible.cfg) = /home/osen/.ansible/tmp/ansible-local-202404c7ukm9k2
DEFAULT_LOG_PATH(/home/osen/projects/ansible-automation/ansible.cfg) = /home/osen/projects/ansible-automation/logs/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/home/osen/projects/ansible-automation/ansible.cfg) = /home/osen/.ssh/id_rsa_ansible
DEFAULT_REMOTE_USER(/home/osen/projects/ansible-automation/ansible.cfg) = ubuntu
DEFAULT_ROLES_PATH(/home/osen/projects/ansible-automation/ansible.cfg) = ['/home/osen/.ansible/roles']
DEFAULT_TIMEOUT(/home/osen/projects/ansible-automation/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/osen/.vault_pass.txt
DEPRECATION_WARNINGS(/home/osen/projects/ansible-automation/ansible.cfg) = False
HOST_KEY_CHECKING(/home/osen/projects/ansible-automation/ansible.cfg) = False
INVENTORY_ENABLED(/home/osen/projects/ansible-automation/ansible.cfg) = ['yaml', 'hetzner.hcloud.hcloud']
INVENTORY_IGNORE_EXTS(/home/osen/projects/ansible-automation/ansible.cfg) = ['~', '.orig', '.bak', '.cfg', '.retry', '.pyc', '.pyo', '.creds']
TRANSFORM_INVALID_GROUP_CHARS(/home/osen/projects/ansible-automation/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT

Ubuntu 22.04 

##### STEPS TO REPRODUCE

add these 2 directives and it will not work

both set to true
```yaml
      delete_protection: "{{ item.delete_protection }}"
      rebuild_protection: "{{ item.rebuild_protection }}"
```

##### EXPECTED RESULTS

so delete protection is active and server cant be easily deleted.

##### ACTUAL RESULTS

on server i dont see delete protection is activated.

```paste below

```

**Comment by jooola** [comment]
@omerfsen Hi,

I cannot reproduce your issue, could you please confirm the version of the collection you are running ?

```sh
ansible-galaxy collection list
```

I ran the following playbook:
```yaml
- name: Test 1
  hosts: localhost
  connection: local
  tasks:
    - name: Create server
      hetzner.hcloud.hcloud_server:
        name: my-server1
        server_type: cx11
        image: ubuntu-22.04
        state: present

    - name: Add server delete protection
      hetzner.hcloud.hcloud_server:
        name: my-server1
        server_type: cx11
        image: ubuntu-22.04
        delete_protection: true
        rebuild_protection: true
        state: present

    - name: Delete server
      hetzner.hcloud.hcloud_server:
        name: my-server1
        state: absent
      ignore_errors: true
      register: result
    - name: Verify delete server
      ansible.builtin.assert:
        that:
          - result is failed

- name: Test 2
  hosts: localhost
  connection: local
  tasks:
    - name: Create server
      hetzner.hcloud.hcloud_server:
        name: my-server2
        server_type: cx11
        image: ubuntu-22.04
        delete_protection: true
        rebuild_protection: true
        state: present

    - name: Delete server
      hetzner.hcloud.hcloud_server:
        name: my-server2
        state: absent
      ignore_errors: true
      register: result
    - name: Verify delete server
      ansible.builtin.assert:
        that:
          - result is failed

```
