### ISSUE TITLE
hcloud_load_balancer reports change every time

### ISSUE THREAD

**Issue by betelgeuse** [ansible-collections/hetzner.hcloud#409]
##### SUMMARY

On every run the load balancer module reports changes

```
changed: [localhost] => {"changed": true
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud_load_balancer 

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.0]
```

##### COLLECTION VERSION

```paste below
Collection     Version
-------------- -------
hetzner.hcloud 2.3.0  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### STEPS TO REPRODUCE

```yaml
    - name: Load Balancer
      hetzner.hcloud.hcloud_load_balancer:
        api_token: "{{ api_token.passphrase }}"
        name: load-balancer
        location: "{{ location }}"
        load_balancer_type: lb11
        state: present
      register: load_balancer
```

##### EXPECTED RESULTS

Report no changes after the first run

##### ACTUAL RESULTS

```paste below
changed: [localhost] => {"changed": true
```
