### ISSUE TITLE
hcloud_volume does not delete volumes

### ISSUE THREAD

**Issue by decentral1se** [ansible-collections/hetzner.hcloud#47]
##### SUMMARY

Volumes are not deleted when destroying servers.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud_volume

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = None
  configured module search path = ['.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = molecule-hetznercloud/.venv/lib/python3.9/site-packages/ansible
  executable location = molecule-hetznercloud/.venv/bin/ansible
  python version = 3.9.0 (default, Dec 11 2020, 22:49:05) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
...empty...
```

##### OS / ENVIRONMENT

GNU/Linux Debian Buster

##### STEPS TO REPRODUCE

```yaml
# create.yml
    - name: Create volume(s)
      hcloud_volume:
        name: "{{ item.1.name | default(item.0.name) }}"
        server: "{{ item.0.name }}"
        location: "{{ item.1.location | default(omit) }}"
        size: "{{ item.1.size | default(10) }}"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
        state: "present"
      loop: "{{ molecule_yml.platforms|subelements('volumes', skip_missing=True)}}"
      register: volumes
      async: 7200
      poll: 0

    - name: Wait for volume(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: hetzner_volumes
      until: hetzner_volumes.finished
      retries: 300
      when:
        - volumes is defined
        - volumes.changed
      with_items: "{{ volumes.results }}"
```

```yaml
# destroy.yml
    - name: Destroy volume(s)
      hcloud_volume:
        name: "{{ item.volumes.name | default(item.instance) }}"
        server: "{{ item.instance }}"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
        state: absent
      register: volumes
      with_items: "{{ instance_conf }}"
      async: 7200
      poll: 0

    - name: Wait for volume(s) deletion to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: hetzner_volumes
      until: hetzner_volumes.finished
      retries: 300
      when: volumes.changed
      with_items: "{{ volumes.results }}"
```

See more in https://github.com/ansible-community/molecule-hetznercloud.

##### EXPECTED RESULTS

Volumes are taken out of attachment and then deleted.

##### ACTUAL RESULTS

Volumes are detached but not deleted.

**Comment by LKaemmerling** [comment]
Hey @decentral1se,

thank you for the report. Based on your playbook and the given code, it looks like the state was not correctly set. 

Deleting an attached volume is not possible and will lead to an error (`volume with ID {volume_id!r} is still attached to a server`) (https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/modules/hcloud_volume.py#L299)

When the `state` is `absent` it will call the delete method (https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/modules/hcloud_volume.py#L333) and as the volume is still attached it will throw the error. For me it looks like in your call `server` was `empty` and the `state` was `present` (maybe because of the default? (https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/modules/hcloud_volume.py#L318) ). It then tries to detach the volume only (https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/modules/hcloud_volume.py#L261). 

I'm not feeling well with automatically detaching the volume on `absent`, because you could delete it unintentionally and this would lead to a dataloss.

**Comment by decentral1se** [comment]
Thanks for taking a look! OK, so as I understand it, the logic here is the same in the web UI. You detach the volume first, delete the instance and then delete the volume after. If I can get that working then I will close this off.

**Comment by decentral1se** [comment]
@LKaemmerling I cannot get volumes to be deleted. Can you reproduce this with the following:

```
git clone https://github.com/ansible-community/molecule-hetznercloud.git
cd molecule-hetznercloud
python3 -m venv .venv && source .venv/bin/activate
pip install -e . "ansible>=2.10, <2.11"
export INSTANCE_UUID=$(openssl rand -hex 5)
export HCLOUD_TOKEN=YOURKEY
cd integration && molecule test
```

An instance is created and a volume is attached. Then, the instance is deleted with the volume still attached. That delets the instance and detaches the volume. Then I try to delete the volume but since the server is gone, the logic fails to delete it? I think it might be https://github.com/ansible-collections/hetzner.hcloud/blob/main/plugins/modules/hcloud_volume.py#L257?

**Comment by adabru** [comment]
I had a similar issue like decentral1se today. Deleting the volume immediately after deleting the server complained with

```
volume with ID '12358xxx' is still attached to a server
```

After a short timeout it worked. I'm using as a workaraound now (first detaching):

```yml
    - name: Gather volume info
      hcloud_volume_info:
        api_token: "{{ vault_hetzner_api_token }}"
        name: myvolume
      register: volume_info
    - name: Detach volume
      hcloud_volume:
        api_token: "{{ vault_hetzner_api_token }}"
        name: myvolume
        location: fsn1
        state: present
        server: "None"
      when: volume_info.hcloud_volume_info | length and volume_info.hcloud_volume_info[0].server != "None"
    - name: Remove volume
      hcloud_volume:
        api_token: "{{ vault_hetzner_api_token }}"
        name: myvolume
        state: absent
    - name: Remove server
      hcloud_server:
        name: myserver
        api_token: "{{ vault_hetzner_api_token }}"
        state: absent
```

> I'm not feeling well with automatically detaching the volume on `absent`, because you could delete it unintentionally and this would lead to a dataloss.

Seems sensible to me. What about some flag like "force_detach: True" or "state: force_absent"?
