### ISSUE TITLE
Ansible doesn't parse specific project or hcloud.yml file

### ISSUE THREAD

**Issue by AndreiPaulau** [ansible-collections/hetzner.hcloud#53]
##### SUMMARY

I have a really weird behavior
I have 3 projects where I use ansible hcloud plugin via "export HCLOUD_TOKEN"
2 of them work as expected.
But one has a strange behavior
export HCLOUD_TOKEN=token1
ansible-inventory -vvv -i app/appname1/prod/prod-hcloud.yml --list
shows group of servers

export HCLOUD_TOKEN=problem_project_token
ansible-inventory -vvv -i app/appname2/prod/prod-hcloud.yml --list
can't parse...

prod-hcloud.yml files differs only by tag label keys
plugin: hcloud
label_selector: "environment=prod, app=appname, tag=tag1"
groups:
  sync: labels["environment"]=="prod" and labels["app"]=="appname" and labels["tag"]=="tag1"

Meanwhile I was able to nock to Hetzner API via the problem token and get my servers info!
Even more I do provision my infra via terraform using the same token...
The only thing I can't do - parse inventory only in one project

+ I've create a bunch of tokens in that project and non of them is working with my inventory file
Ok, i thought that something wrong with my inventory file and I export token from other project and did 
ansible-inventory -vvv -i app/appname2/prod/prod-hcloud.yml --list
surely it doesn't show servers since there is no server with such labels, but it didn't error at least

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud used for ansible dynamic inventory

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(env: ANSIBLE_GATHERING) = smart
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

Ubuntu 20.04.1 LTS (Focal Fossa)

##### STEPS TO REPRODUCE

```yaml
export HCLOUD_TOKEN=token_with_rw_generated_in_project_console
ansible-inventory -i app/appname/dev/dev-hcloud.yml --list

**dev-hcloud.yml**
plugin: hcloud
label_selector: "environment=dev, app=appname, tag=tag1"
groups:
  sync: labels["environment"]=="dev" and labels["app"]=="appname" and labels["tag"]=="tag1"
At least shows that there is no such servers without errors

ansible-inventory -i app/appname/prod/prod-hcloud.yml --list

**prod-hcloud.yml**
plugin: hcloud
label_selector: "environment=prod, app=appname, tag=tag2"
groups:
  sync: labels["environment"]=="prod" and labels["app"]=="appname" and labels["tag"]=="tag2"
```
Shows output:
[WARNING]:  * Failed to parse app/appname/prod/prod-hcloud.yml with auto plugin: 'NoneType' object has no attribute 'name'
[WARNING]:  * Failed to parse app/appname/prod/prod-hcloud.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse app/appname/prod/prod-hcloud.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is
reserved to provide a port.
[WARNING]: Unable to parse app/appname/prod/prod-hcloud.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available

Token hasn't been changed while execution of both commands

2 other projects has mirrored configuration where i change app labels

##### ACTUAL RESULTS

```paste below

```
