### ISSUE TITLE
hcloud_server: traceback when state=started in diff mode

### ISSUE THREAD

**Issue by resmo** [ansible-collections/hetzner.hcloud#54]
##### SUMMARY
Non exisitng server with state=started and check mode fails with traceback
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'status'
fatal: [mail1.ngine.ch]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_payload_s8f9ff5_/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 564, in <module>\n  File \"/tmp/ansible_hcloud_server_payload_s8f9ff5_/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 548, in main\n  File \"/tmp/ansible_hcloud_server_payload_s8f9ff5_/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 454, in start_server\nAttributeError: 'NoneType' object has no attribute 'status'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud_server
##### ANSIBLE VERSION

```paste below
ansible 3.0.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: create server with ssh key
  hcloud_server:
    name: "{{ hcloud_server_name }}"
    server_type: "{{ hcloud_server_type }}"
    image: "{{ hcloud_server_image }}"
    location: "{{ hcloud_server_location }}"
    ssh_keys: "{{ hcloud_ssh_key_name }}"
    api_token: "{{ hcloud_api_token or omit }}"
    state: started
  register: server
```

##### EXPECTED RESULTS

no traceback

##### ACTUAL RESULTS

traceback

```paste below

```

**Comment by LKaemmerling** [comment]
@resmo can you reproduce this with the latest collection release?

**Comment by resmo** [comment]
@LKaemmerling let me check

**Comment by resmo** [comment]
its worse ;)

before I only got a straceback if the host didn't exist: now I get a trace back even for existing hosts:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not callable
fatal: [mon1.ngine.ch]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_payload_zorofo9g/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 614, in <module>\n  File \"/tmp/ansible_hcloud_server_payload_zorofo9g/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 597, in main\n  File \"/tmp/ansible_hcloud_server_payload_zorofo9g/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 538, in present_server\n  File \"/tmp/ansible_hcloud_server_payload_zorofo9g/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 333, in _create_server\n  File \"/tmp/ansible_hcloud_server_payload_zorofo9g/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 334, in <listcomp>\nTypeError: 'NoneType' object is not callable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by LKaemmerling** [comment]
```
--- 
- hosts: localhost
  tasks:
  - name: create server with ssh key
    hetzner.hcloud.hcloud_server:
        name: "test"
        server_type: "cx11"
        image: "ubuntu-20.04"
        location: "nbg1"
        ssh_keys: "ci@ansible.hetzner.cloud"
        state: started
    register: server
```

Using the sample above i can not encounter this problem,  what are the specific values you use?
