### ISSUE TITLE
Size and region are missing on module args, but I can't find a reference to them anywhere

### ISSUE THREAD

**Issue by ijpatricio** [ansible-collections/hetzner.hcloud#566]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.5]
  config file = /ansible/ansible.cfg
  configured module search path = ['/etc/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /etc/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.7 (main, Oct  2 2024, 00:14:14) [GCC 10.2.1 20210110] (/usr/local/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
hetzner.hcloud                           3.1.1
```

##### CONFIGURATION

```paste below
ANSIBLE_HOME(env: ANSIBLE_HOME) = /etc/ansible
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/etc/ansible/collections']
CONFIG_FILE() = /ansible/ansible.cfg
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/hosts']
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Running in a docker image: serversideup/latest

##### STEPS TO REPRODUCE

I'm running a playbook which includes the task below, and it seems the payload is invalid.
You may remove the `user_data` bc it's optional

```yaml
- name: Create a new Server
  hosts: localhost
  vars_files:
    - hetzner-secrets.yml

  tasks:

    - name: Generate SHA-512 password hash
      ansible.builtin.set_fact:
        USER_PASSWORD_HASH: "{{ USER_PASSWORD | password_hash('sha512') }}"
      no_log: true

    # https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/server_module.html#ansible-collections-hetzner-hcloud-server-module
    - name: Create a new Server
      community.digitalocean.digital_ocean_droplet:
        state: present
        wait_timeout: 500
        api_token: "{{ HETZNER_API_TOKEN }}"
        backups: "{{ BACKUPS }}"
        image: "{{ IMAGE }}"
        name: "{{ NAME }}"
        datacenter: "{{ DATACENTER }}"
        server_type: "{{ SERVER_TYPE }}"
        ssh_keys: "{{ HETZNER_SSH_KEYS }}"
        user_data: "{{ lookup('template', 'cloud-config.yml.j2') }}"
      register: my_server
```

##### EXPECTED RESULTS

I expected the server to be created, as per docs on:
https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/server_module.html#ansible-collections-hetzner-hcloud-server-module
and
https://docs.hetzner.cloud/#servers-create-a-server

##### ACTUAL RESULTS

Even on  https://docs.hetzner.cloud/#servers-create-a-server and seems that `region` and `size` aren't mentioned anywhere as required parameters

This curl command is able to create a server successfully
```
curl \
	-X POST \
	-H "Authorization: Bearer $API_TOKEN" \
	-H "Content-Type: application/json" \
	-d '{"automount":false,"datacenter":"nbg1-dc3","image":"ubuntu-20.04","name":"my-server","server_type":"cpx11","start_after_create":true}' \
	"https://api.hetzner.cloud/v1/servers"

```

But not the playbook above.

Here is the error part of the output (-vvvv)

![CleanShot 2024-10-09 at 10 17 32](https://github.com/user-attachments/assets/43e81fb7-1e26-4470-927a-ba90bbc0131a)

Thank you in advance
