### ISSUE TITLE
server is rebuilt unnecessarily

### ISSUE THREAD

**Issue by asarubbo** [ansible-collections/hetzner.hcloud#580]
My MANIFEST.json reports 2.5.0, (so a bit old, I know).

I have somthing like:

```
    - name: Create the server on hetzner-cloud
      hcloud_server:
        <snip>
        state: rebuild
```

According to the hcloud panel data(activities) I can see:

```
server.rebuild
server.create
```

So in short, `state: rebuild` is rebuilding the server also when it was never created.
I think this an unnecessary step.
