### ISSUE TITLE
hetzner.hcloud.certificate reports no changes on differing certificate

### ISSUE THREAD

**Issue by betelgeuse** [ansible-collections/hetzner.hcloud#588]
##### SUMMARY

hetzner.hcloud.certificate reports no changes after changing the certificate parameter for type=uploaded

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hetzner.hcloud.certificate

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.0]
  config file = /Users/betelgeuse/.ansible.cfg
  configured module search path = ['/Users/betelgeuse/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/betelgeuse/.local/pipx/venvs/ansible/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/betelgeuse/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/betelgeuse/.local/bin/ansible
  python version = 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.4)] (/Users/betelgeuse/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/betelgeuse/.ansible/collections/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 4.2.2  

# /Users/betelgeuse/.local/pipx/venvs/ansible/lib/python3.13/site-packages/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 4.2.1
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/betelgeuse/.ansible.cfg) = True
CALLBACKS_ENABLED(/Users/betelgeuse/.ansible.cfg) = ['timer', 'profile_tasks', 'profile_roles']
CONFIG_FILE() = /Users/betelgeuse/.ansible.cfg

GALAXY_SERVERS:
```

##### STEPS TO REPRODUCE

```yaml
- name: Add Certificate to HCloud
  tags: certs
  hetzner.hcloud.hcloud_certificate:
    name: certificate
    type: uploaded
    state: present
    certificate: |
        NEW_CERTIFICATE_VALUE
    private_key: |
        NEW_PRIVATE_KEY_VALUE
```

##### EXPECTED RESULTS

Certificate gets updated to the new values.

##### ACTUAL RESULTS

```paste below
ok: [load-balancer] => {
    "changed": false,
```
