### ISSUE TITLE
Use vault variable for hcloud token in plugin configuration 

### ISSUE THREAD

**Issue by ieugen** [ansible-collections/hetzner.hcloud#61]
##### SUMMARY

I would like to keep my hcloud token in ansible vault so it is encrypted.
I would like to use the token to configure hcloud ansible plugin for dynamic inventory.

This does not work currently. 

Is there any way to have this working so I can have all secrets for the project in a single place?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hetzner.hcloud.hcloud

##### ADDITIONAL INFORMATION

I've installed 
```yaml
- name: hetzner.hcloud
    version: 1.2.1
```
An my configuration is: 
```yaml
plugin: hetzner.hcloud.hcloud
token: "{{ vault_hcloud_token }}"
keyed_groups:
  - key: location
    prefix: hcloud_location
  - key: image_os_flavor
    separator: ""
  - key: status
    prefix: server_status
```

I think this is related/alternative to my issue  https://github.com/ansible-collections/hetzner.hcloud/issues/48 . 

I did found this which is not encouraging:

https://stackoverflow.com/questions/63166542/use-variable-in-ansible-inventory-aws-plugin
 "
group_vars and inventory files are not evaluated by jinja2, so you cannot use mustache expressions in them like that; if you have a dynamic inventory you can do anything that your programming language allows you to do – mdaniel Jul 30 '20 at 16:02
"
