### ISSUE TITLE
ERROR! couldn't resolve module/action 'hcloud_firewall'

### ISSUE THREAD

**Issue by papanito** [ansible-collections/hetzner.hcloud#76]
##### SUMMARY

Unable to use `hcloud_firewall` as play fails with
```bash
ERROR! couldn't resolve module/action 'hcloud_firewall'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/aedu/Workspaces/example.com/infrastructure/hetzner_firewall.yml': line 11, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  pre_tasks:
  - name: Ensure Firewall is setup
    ^ here
```

Latest collection is installed

```bash
# /home/aedu/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.netcommon     2.0.1  
ansible.utils         2.0.2  
community.general     2.4.0  
community.hrobot      1.1.1  
geerlingguy.php_roles 1.0.0  
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`hetzner.hcloud`

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
  config file = /home/aedu/ansible.cfg
  configured module search path = ['/home/aedu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/aedu/ansible.cfg) = ['/home/aedu/inventory.yml']
DEFAULT_REMOTE_USER(/home/aedu/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/aedu/ansible.cfg) = ['/home/aedu/roles']
DEFAULT_TIMEOUT(/home/aedu/ansible.cfg) = 10
DEFAULT_VAULT_PASSWORD_FILE(/home/aedu/ansible.cfg) = /home/aedu/.ssh/mykey
GALAXY_SERVER_LIST(/home/aedu/ansible.cfg) = ['release_galaxy']
RETRY_FILES_SAVE_PATH(/home/aedu/ansible.cfg) = /home/aedu/.ansible-retry
```

##### OS / ENVIRONMENT

`Linux 5.11.10-1-MANJARO x86_64 GNU/Linux`

##### STEPS TO REPRODUCE

Run `ansible-playbook firewall.yml`

```yaml
---
- hosts: localhost
  become: no
  gather_facts: false
  vars:
    hcloud_server_image: "debian-10"
    hcloud_server_type: "cx11"
    hcloud_firewall_name: "firewall-ssh-only"

  pre_tasks:
  - name: Ensure Firewall is setup
    hcloud_firewall:
      api_token: "{{ hcloud_token }}"
      name: "{{ hcloud_firewall_name }}"
      public_key: "{{ item.value }}"
      state: present
      rules:
        ssh:
          directions: "in"
          port: "22"
          protocol: "tcp"
    delegate_to: localhost

```

##### EXPECTED RESULTS

Firewall instance is created

##### ACTUAL RESULTS

```bash
> ansible-playbook hetzner_firewall.yml -vvvv
ansible-playbook 2.10.7
  config file = /home/aedu/Workspaces/example.com/infrastructure/ansible.cfg
  configured module search path = ['/home/aedu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Using /home/aedu/Workspaces/example.com/infrastructure/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/aedu/Workspaces/example.com/infrastructure/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/aedu/Workspaces/example.com/infrastructure/inventory.yml as it did not pass its verify_file() method
Parsed /home/aedu/Workspaces/example.com/infrastructure/inventory.yml inventory source with yaml plugin
setting up inventory plugins
host_list declined parsing /home/aedu/Workspaces/example.com/infrastructure/inventory.hcloud.yml as it did not pass its verify_file() method
script declined parsing /home/aedu/Workspaces/example.com/infrastructure/inventory.hcloud.yml as it did not pass its verify_file() method
redirecting (type: inventory) ansible.builtin.hcloud to hetzner.hcloud.hcloud
Loading collection hetzner.hcloud from /home/aedu/.ansible/collections/ansible_collections/hetzner/hcloud
Parsed /home/aedu/Workspaces/example.com/infrastructure/inventory.hcloud.yml inventory source with auto plugin
ERROR! couldn't resolve module/action 'hcloud_firewall'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/aedu/Workspaces/example.com/infrastructure/hetzner_firewall.yml': line 11, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  pre_tasks:
  - name: Ensure Firewall is setup
    ^ here
```

**Comment by LKaemmerling** [comment]
@papanito you need to specify the full name module name. hetzner.hcloud.hcloud_firewall. Using the short name is only supported for Modules the were within the Ansible core before the split. The firewall module is too new.

also it looks like the Collection is not installed.

**Comment by papanito** [comment]
Again @LKaemmerling for the quick help, was not aware when it requires the full module name. But once corrected this works just fine
```yaml
---
- hosts: localhost
  become: no
  gather_facts: false
  vars:
    hcloud_firewall_name: "firewall-ssh-only"

  pre_tasks:
  - name: Ensure Firewall is setup
    hetzner.hcloud.hcloud_firewall:
      api_token: "{{ hcloud_token }}"
      name: "{{ hcloud_firewall_name }}"
      state: present
      rules:
        - direction: "in"
          port: "22"
          protocol: "tcp"
          source_ips:
            - 0.0.0.0/0
            - ::/0
    delegate_to: localhost
```
