### ISSUE TITLE
Update Firewall on existing server results in AttibuteError

### ISSUE THREAD

**Issue by cbreit** [ansible-collections/hetzner.hcloud#94]
##### SUMMARY
When updating the firewall config of an existing server, the ansible hcloud_server role runs into an AttributeError.
Applying an firewall to a newly created server also has no effect.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hetzner.hcloud.hcloud_server

##### ANSIBLE VERSION

```
ansible [core 2.11.2] 
  config file = /home/breidi/coding/ansible-provisioning/ansible.cfg
  configured module search path = ['/home/breidi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/breidi/.ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True

```

##### COLLECTION VERSION

```
hetzner.hcloud 1.4.3
```

##### CONFIGURATION

```
COLLECTIONS_PATHS(ansible.cfg) = ['~/.ansible/collections']
COLLECTIONS_SCAN_SYS_PATH(ansible.cfg) = False
HOST_KEY_CHECKING(ansible.cfg) = False
INTERPRETER_PYTHON(ansible.cfg) = auto
```

##### OS / ENVIRONMENT
Debian Sid
Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-1 (2021-06-24) x86_64 GNU/Linux

##### STEPS TO REPRODUCE
 - create firewall-1 (empty)
 - create firewall-2 (with some rules)
 - create VM with firewall-1 applied
 - apply firewall-2 on created VM

```yaml
  tasks:
    - name: Create firewall-1
      hetzner.hcloud.hcloud_firewall:
        name:   "fw-1"
        state: present
      register: fw_1_result

    - name: Create firewall-2
      hetzner.hcloud.hcloud_firewall:
        name:   "fw-2"
        state: present
        rules:
          - direction: in
            protocol: tcp
            port: "22"
            source_ips:
              - 0.0.0.0/0
      register: fw_2_result

    - name: Create servers
      hetzner.hcloud.hcloud_server:
        name:   "srv-1"
        server_type: "cx11"
        image: "debian-10"
        firewalls:
          - "{{ fw_1_result.hcloud_firewall.id }}"

    - name: Apply fw-2
      hetzner.hcloud.hcloud_server:
        name:   "srv-1"
        state: present
        firewalls:
          -  "{{ fw_2_result.hcloud_firewall.id }}"
```

##### EXPECTED RESULTS
Applying/changing a firewall works.

##### ACTUAL RESULTS
Initial firewall is not applied to the created server. Applying a firewall results in an error.

```
Traceback (most recent call last):
  File "/tmp/ansible_hetzner.hcloud.hcloud_server_payload_irhqjgji/ansible_hetzner.hcloud.hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 480, in _update_server
  File "/usr/local/lib/python3.9/dist-packages/hcloud/firewalls/client.py", line 341, in apply_to_resources
    url="/firewalls/{firewall_id}/actions/apply_to_resources".format(firewall_id=firewall.id),
AttributeError: 'NoneType' object has no attribute 'id'

```
